spring:
  application:
    name: logger-server
  profiles:
    active: dev

logging:
  level:
    root: INFO
    com.szzh.loggerserver: INFO

logger-server:
  protocol:
    max-payload-size: 102400
    messages:
      # broadcast-global 仿真任务管理消息
      global:
        # 类型编号
        message-type: 0
        # 任务创建
        create-message-code: 0
        # 任务停止
        stop-message-code: 1

      # broadcast-{ScenarioInstanceID} 仿真控制指令
      control:
        # 类型编号
        message-type: 1100
        # 仿真启动控制指令
        start-message-code: 1
        # 仿真暂停控制指令
        pause-message-code: 5
        # 继续仿真控制指令
        resume-message-code: 6
  session:
    cleanup-delay-seconds: 30
  write:
    retry-times: 3
    batch-size: 500
